### ISSUE TITLE
SSLHandshakeException in Bynder Upload Java SDK

### ISSUE THREAD

**Issue by 212778826** [Bynder/bynder-java-sdk#98] opened 2022-12-12 11:29 UTC
Hi Team,

We are using Bynder Java SDK in our  custom bynder java (spring boot) upload application. We are facing below issue in Upload process and below error has been observed.

ava.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Observable.blockingSingle(Observable.java:5381) ~[rxjava-2.2.21.jar:na]
	at com.bh.dam.service.impl.UploadWorkSDK.uploadProcess(UploadWorkSDK.java:173) [classes/:0.0.1-SNAPSHOT]
	at com.bh.dam.service.impl.UploadWorkSDK.call(UploadWorkSDK.java:49) [classes/:0.0.1-SNAPSHOT]
	at com.bh.dam.service.impl.UploadWorkSDK.call(UploadWorkSDK.java:30) [classes/:0.0.1-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_20]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_20]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_20]

Custom class file calling to OOTB Java SDK upload Method
UploadWorkSDK.java:173
saveMediaResponse = client.getAssetService().uploadFile(uploadQuery).blockingSingle();

OOTB Java SDK code
/**
     * Uploads a file with the information specified in the query parameter.
     *
     * @param uploadQuery Upload query with the information to upload the file.
     * @return {@link Observable} with the {@link SaveMediaResponse} information.
     */
    public Single<SaveMediaResponse> uploadFile(final UploadQuery uploadQuery) {
        return getClosestS3Endpoint().flatMap(awsBucket -> {
            String filename = uploadQuery.getFilename();
            AmazonS3Service amazonS3Service = AmazonS3Service.Builder.create(awsBucket);
            return getUploadInformation(new RequestUploadQuery(filename))
                    .flatMap(uploadRequest -> uploadChunk(
                            amazonS3Service,
                            uploadRequest,
                            uploadQuery,
                            filename
                    ).count().flatMap(chunkCount -> finaliseUpload(new FinaliseUploadQuery(
                            uploadRequest.getS3File().getUploadId(),
                            uploadRequest.getS3File().getTargetId(),
                            uploadRequest.getS3Filename(),
                            chunkCount
                    ))));
        }).flatMap(importId ->
                pollProcessing(importId).andThen(saveUploadedMedia(importId, uploadQuery))
        );
    }

Kindly suggest how can resolve this isse.

**Comment by TimBloembergen** [comment] 2022-12-12 12:06
Hi @212778826 We've had a look and determined that this isn't an issue with the SDK. We've had a user running into a similar issue before, please have a look at https://github.com/Bynder/bynder-java-sdk/issues/13 to see if this resolves it for you as well.

**Comment by Arpit-Sharma-USC** [comment] 2022-12-12 12:08
You seem to be missing `cacerts` needed for this request in your jvm. This is a useful thread on how to add it:
https://mirkasimali80.blogspot.com/2011/02/web-service-lookup-over-ssl-about-web.html

Like Tim mentioned above, we had a similar issue in the past #13 so maybe there is a thread to pull on there for you. 
Alternatively you can ignore that by hacking your jvm config via `-Dcom.sun.security.enableAIAcaIssuers=true` see [here](https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore)

**Comment by 212778826** [comment] 2022-12-12 13:07
Thanks Tim & Arpit for resolution.

I`ll go through suggested link but the interesting thing is we didn`t see this issue for sandbox instance. example our sandbox instance is "bakerhughessandbox.getbynder.com". 

However the code case same and Bydner URL we are passing through configuration file. If passing sandbox URL it is working fine without any issue but when passing Production Bynder URL in runtime, its filling up log file "SSLHandshakeException".  That`s my worry point.

Y`day i have already added  .cer (certificate) by below command and able to see when retrieving ,cer list by keytool.
_**keytool -import -alias bhprodbynder.cer -keystore  "C:\Program Files\Java\jdk1.8.0_351\jre\lib\security\cacerts" -file D:\CertificateForBynder\production_**_

One more observation, prior to upload we are sending one call to Bynder DAM system to get total media count and where we can see response from Bynder DAM system (Production).

And idea why that getMedia call is working for PROD and why "upload" call is falling.?

**Comment by TimBloembergen** [comment] 2022-12-12 13:37
@212778826 The only difference that I see is that the production environment is not using a certificate issued by us (Amazon) but it's a custom one, typically this shouldn't cause any issues with the API as we don't control that.

**Comment by nitin1edate** [comment] 2022-12-12 13:38
In related to above issue, We are getting mediaId's through API and we have added the code to bypass SSL certificate and it works fine. But for upload functionality, we are using SDK and when using SDK we are getting  'SSLHandshakeException' exception.

**Comment by TimBloembergen** [comment] 2022-12-12 14:33
@nitin1edate We just tested on the BH production portal with the JAVA sdk and we were able to upload just fine, this is the mediaID of the file that we uploaded, 83D9A79A-94A3-4E62-95344BC3D0E517E2. It seems there's something locally on the machine that you are using the SDK on in regards to certificates. Unfortunately it's not something we can assist with since we cannot reproduce.

**Comment by nitin1edate** [comment] 2022-12-12 14:38
Thanks for reply.

From my local machine, it is working fine. Also we did UAT testing  in sandbox and looked fine. But when we tried the same in production, we are getting the above issue.

**Comment by TimBloembergen** [comment] 2022-12-12 14:42
@nitin1edate What we can recommend in this case is to review the links Arpit mentioned above or see if others ran into similar issues with any JAVA code and SSL issues on sites such as stackoverflow. What are you running into at the moment is not related to the SDK, this unfortunately means we cannot really assist, we can only provide advise to a certain extend.

**Closed** 2023-01-03 08:51 UTC
