### ISSUE TITLE
ApiFactory: Loading bynder-sdk.properties fails in Tomcat

### ISSUE THREAD

**Issue by dSeidel** [Bynder/bynder-java-sdk#38] opened 2020-11-26 15:40 UTC
Hi,
I use the Bynder Java SDK in a webapp running in Tomcat. Updating to 2.2.4 is not possible, since the code fails to read the `bynder-sdk.properties` using `ClassLoader.getSystemResourceAsStream("bynder-sdk.properties")` (`com.bynder.sdk.api.ApiFactory`, line 202).

Replacing via `ApiFactory.class.getClassLoader().getResourceAsStream("/bynder-sdk.properties")` would solve the problem.

**Comment by githuib** [comment] 2020-11-30 16:25
Hi @dSeidel ,
I've tried your solution using the `/` prefix, but unfortunately that doesn't work when you would used it in other types of environments than Tomcat.

I wondered though, what happens when you try this?
```
Thread.currentThread().getContextClassLoader().getResourceAsStream("bynder-sdk.properties")
```

**Comment by dSeidel** [comment] 2020-12-01 07:34
Hi @githuib, I just tried your suggestion and it works as well. Thanks for the quick answer :).

**Comment by githuib** [comment] 2020-12-01 09:59
Thanks for trying it, we'll solve this issue in the upcoming release.

**Comment by Ben-Zahler** [comment] 2020-12-04 15:48
hi @githuib I don't think this is properly fixed in 2.2.25.
I'm running the Bynder SDK in Adobe Experience Manager and I get the same message:
Caused by: java.io.IOException: bynder-sdk.properties could not be loaded.
        at com.bynder.sdk.util.Utils.loadConfig(Utils.java:70) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at com.bynder.sdk.api.ApiFactory.lambda$addUserAgentHeader$2(ApiFactory.java:201) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:144) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at com.bynder.sdk.api.ApiFactory.lambda$setPermanentTokenInterceptor$1(ApiFactory.java:151) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at okhttp3.RealCall.execute(RealCall.java:69) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at io.reactivex.Observable.subscribe(Observable.java:10841) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:30) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at io.reactivex.Maybe.subscribe(Maybe.java:3724) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]
        at io.reactivex.Maybe.blockingGet(Maybe.java:2007) [ch.codeflair.bynder-aem.core:1.3.0.SNAPSHOT]

**Comment by githuib** [comment] 2020-12-04 17:41
@Ben-Zahler is this only happening for you since 2.2.5, or also in earlier versions? If so, I would have some ideas to fix this, but I hope you can revert to an earlier version for the time being.

**Comment by Ben-Zahler** [comment] 2020-12-04 18:05
@githuib it works in 2.2.3, so I'm not blocked.

**Comment by githuib** [comment] 2020-12-04 18:43
Should be fixed by https://github.com/Bynder/bynder-java-sdk/pull/40

**Comment by githuib** [comment] 2020-12-07 16:24
@Ben-Zahler The issue you're having since versions > 2.2.3 should be addressed in 2.2.6 which was just released.

**Closed** 2020-12-09 13:35 UTC
Labels: bug

**Comment by Ben-Zahler** [comment] 2020-12-10 11:06
@githuib I only tested this today, it's still ocurring.
I am aware that AEM is quite a special Java container, so I'm happy to help solving this.
However, I'm unsure about that root cause of this:
- should the config property "bynder-sdk.properties" be present?
- or should the code also work when this property is not present?

**Comment by githuib** [comment] 2020-12-22 14:04
Hi @Ben-Zahler This file was added as part of a mechanism to send the SDK name and version along API requests, so we can have a better overview if API calls come from one of the SDKs or from somewhere else for example.

It is not critical for the SDK, so I was thinking of disabling that mechanism when bynder-sdk.properties could not be loaded for some reason. I'm working on a pull request for that, so I'll keep you posted.

**Comment by githuib** [comment] 2020-12-23 20:56
@Ben-Zahler The new 2.2.7 release should resolve the issue. So please let us know, might this still not work for you.
